
title: My Resume
url: 'https://rudysetiawansif.github.io/'
baseurl: '/RudySetiawan' #change it according to your repository name



# Profile information
yourname: Rudy Setiawan  ## put your name
<<<<<<< HEAD
title: 'Sistem informasi'  ## your title
location: Riau , Indonesia
=======
title: 'Information System, UIN SUSKA'  ## your title
location: Pekanbaru , Riau


## Social Profiles
facebook: https://www.facebook.com/Rudhy87  ## your facebook account url
twitter: https://www.github.com/rudysetiawansif
linkedin: https://www.linkedin.com/in/rudy-setiawan-0a9725152/ ## your linkedin account url



# Update all the sections by editing the files inside _includes folder.
