
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Rudy Setiawan  ## put your name
title: 'Information System, UIN SUSKA'  ## your title
location: Pekanbaru , Riau


## Social Profiles
facebook: http://www.facebook.com/Rudhy87  ## your facebook account url
#twitter: http://www.twitter.com  ## your twitter account url
linkedin: https://www.linkedin.com/in/rudy-setiawan-0a9725152/ ## your linkedin account url
#dribbble: http://www.dribble.com  ## you dribbble account url
#foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
